services:
  test_configuration_service:
    image: wcs-ok2-shipment:latest
    container_name: wcs-ok2-shipment
    # restart: always
    tty: true

    network_mode: "host"

    # ports: 
    #   - "59900:59900" # 必要に応じてポートを変更 59900:59900 (岡崎)
    volumes:
      - ./app_factory.py:/app/app_factory.py # ホストディレクトリの設定ファイルをDockerコンテナにマウント（必要であれば変更）
      - ./app/config/config.py:/app/app/config/config.py
      - ./app/controller_runner/run_controll.py:/app/app/controller_runner/run_controll.py
      - ./app/controllers:/app/app/controllers
      - ./app/domain:/app/app/domain
      - ./app/infrastructure:/app/app/infrastructure
      - ./app/interfaces:/app/app/interfaces
      - ./app/logs:/app/app/logs
      - ./app/services:/app/app/services
      - ./app/static:/app/app/static
      - ./app/templates:/app/app/templates
    command: sh -c "python /app/app_factory.py"

    # networks:
    #   test_network:
    #     ipv4_address: 172.49.0.4
    deploy:
      resources:
        limits:
          memory: 600m

networks:
  test_network:
    name: test_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.49.0.0/24
